// Code generated by "go-gen-getter -type=ExampleStruct"; DO NOT EDIT.

package example

func (e *ExampleStruct) GetField1() time.Time {
	return e.Field1
}
func (e *ExampleStruct) GetField2() string {
	return e.Field2
}
